export const DEFAULT_THEME_COLOR = '#990001';

export const PRESET_THEME_COLORS = [
    { name: 'AO3 Red', color: '#990001' },
    { name: 'Crimson', color: '#e11d48' },
    { name: 'Orange', color: '#ea580c' },
    { name: 'Amber', color: '#d97706' },
    { name: 'Emerald', color: '#16a34a' },
    { name: 'Teal', color: '#0d9488' },
    { name: 'Blue', color: '#2563eb' },
    { name: 'Indigo', color: '#4f46e5' },
    { name: 'Purple', color: '#7c3aed' },
    { name: 'Pink', color: '#db2777' },
];

export const themes = {
    light: {
        name: 'light',
        backgroundColor: '#ffffff',
        textColor: '#171717',
        secondaryTextColor: '#525252',
        placeholderColor: '#a3a3a3',
        headerBackground: '#ffffff',
        cardBackground: '#ffffff',
        inputBackground: '#f5f5f5',
        buttonBackground: '#f5f5f5',
        borderColor: '#e5e5e5',
        primaryColor: DEFAULT_THEME_COLOR,
        iconColor: '#525252',
        tagBackground: '#fee2e2',
        tagTextColor: '#990001',
        warningBackground: '#fee2e2',
        warningTextColor: '#b91c1c',
        warningMessageBackground: '#fef3c7',
        warningMessageTextColor: '#b45309',
        successColor: '#16a34a',
        tagSelectedBackground: '#dcfce7',
        tagSelectedTextColor: '#15803d',
        tagExcludedBackground: '#fee2e2',
        tagExcludedTextColor: '#b91c1c',
        statusBadge: {
            clicked: '#f59e0b',
            started: DEFAULT_THEME_COLOR,
            finished: '#16a34a',
        },
    },
    dark: {
        name: 'dark',
        backgroundColor: '#121212',
        textColor: '#f5f5f5',
        secondaryTextColor: '#a3a3a3',
        placeholderColor: '#737373',
        headerBackground: '#181818',
        cardBackground: '#1e1e1e',
        inputBackground: '#262626',
        buttonBackground: '#282828',
        borderColor: '#333333',
        primaryColor: DEFAULT_THEME_COLOR,
        iconColor: '#a3a3a3',
        tagBackground: '#2b1414',
        tagTextColor: '#fca5a5',
        warningBackground: '#3b1414',
        warningTextColor: '#fca5a5',
        warningMessageBackground: '#2e1b0a',
        warningMessageTextColor: '#fbbf24',
        successColor: '#22c55e',
        tagSelectedBackground: '#193320',
        tagSelectedTextColor: '#86efac',
        tagExcludedBackground: '#3b1414',
        tagExcludedTextColor: '#fca5a5',
        statusBadge: {
            clicked: '#f59e0b',
            started: DEFAULT_THEME_COLOR,
            finished: '#22c55e',
        },
    },
    black: {
        name: 'black',
        backgroundColor: '#000000',
        textColor: '#ffffff',
        secondaryTextColor: '#888888',
        placeholderColor: '#555555',
        headerBackground: '#080808',
        cardBackground: '#0c0c0c',
        inputBackground: '#161616',
        buttonBackground: '#161616',
        borderColor: '#222222',
        primaryColor: DEFAULT_THEME_COLOR,
        iconColor: '#888888',
        tagBackground: '#200808',
        tagTextColor: '#fca5a5',
        warningBackground: '#2a0c0c',
        warningTextColor: '#ffcdd2',
        warningMessageBackground: '#241200',
        warningMessageTextColor: '#f59e0b',
        successColor: '#22c55e',
        tagSelectedBackground: '#102b15',
        tagSelectedTextColor: '#c8e6c9',
        tagExcludedBackground: '#2a0c0c',
        tagExcludedTextColor: '#ffcdd2',
        statusBadge: {
            clicked: '#f59e0b',
            started: DEFAULT_THEME_COLOR,
            finished: '#22c55e',
        },
    },
};

themes.white = themes.light;

export function getThemeWithColor(themeName, customColor) {
    const base = themes[themeName] || themes.light;
    const color = customColor || base.primaryColor || DEFAULT_THEME_COLOR;
    return {
        ...base,
        primaryColor: color,
        statusBadge: {
            ...base.statusBadge,
            started: color,
        },
    };
}
